# Generated by Django 5.2.17 on 2026-09-21 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_livro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='preco',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='quantidade',
        ),
    ]
