# Generated by Django 5.2.17 on 2026-09-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_livro_preco_remove_livro_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('reservado', 'Reservado')], default='disponivel', max_length=20),
        ),
    ]
