# Generated by Django 5.2.17 on 2026-09-22 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_livro_capa'),
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foto',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_foto', to='uploader.image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Indica que este usuário pode acessar o Admin', verbose_name='Usuário é da equipe'),
        ),
    ]
