# Generated by Django 5.2.17 on 2026-09-23 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_itensreserva'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itensreserva',
            old_name='compra',
            new_name='reserva',
        ),
    ]
