# Generated by Django 5.2.17 on 2026-09-23 13:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_compra_itensreserva_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
