# Generated by Django 5.2.17 on 2026-09-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_reserva_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='data',
            new_name='data_criacao',
        ),
        migrations.AddField(
            model_name='reserva',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
