# Generated by Django 5.2.17 on 2026-09-23 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_data_reserva_data_criacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itensreserva',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_reserva', to='core.livro'),
        ),
    ]
