# Generated by Django 5.2.17 on 2026-09-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_livro_sinopse'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='quantidade',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
