# Generated by Django 5.2.17 on 2026-10-01 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_livro_quantidade'),
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.ForeignKey(blank=True, default='./media/default/userDefault.png', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_foto', to='uploader.image'),
        ),
    ]
