# Generated by Django 5.2.17 on 2026-10-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_user_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.IntegerField(choices=[(1, 'Reservado'), (2, 'Retirado'), (3, 'Devolvido'), (4, 'Cancelado')], default=1),
        ),
    ]
