# Generated by Django 5.2.17 on 2026-10-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_user_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Indica que este usuário está ativo.', verbose_name='Usuário está ativo'),
        ),
    ]
