# Generated by Django 5.2.17 on 2026-10-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='formato',
            field=models.CharField(choices=[('livro', 'Livro'), ('revista', 'Revista'), ('apostila', 'Apostila'), ('manual', 'Manual'), ('norma_tecnica', 'Norma técnica')], default='livro', max_length=20, verbose_name='Formato'),
        ),
    ]
